### ISSUE TITLE
Going back deletes data

### ISSUE THREAD

**Issue by KangarooKoala** [robototes/ScoutingApp#4]
When match scouting, it's relatively common to want to go to a previous section to edit a response. However, values are not loaded when going back, making such editing difficult (since the scout must remember all of the other data).
It should be noted, though, that being able to clear data is convenient during demos, so adding a clear button may be useful once going back doesn't clear the data.

**Comment by galaxygoldfish** [comment]
Do you think it would be a good idea to have the clear button at the bottom of all templates, or maybe even have it as a component that you can choose to include in the templates?

**Comment by KangarooKoala** [comment]
I'd say always having it at the bottom makes more sense.

**Comment by galaxygoldfish** [comment]
just did a few more tests apparently the data does not in fact clear when hitting the clear button because the view is not triggered to recompose, currently figuring out how to make that happen

**Comment by galaxygoldfish** [comment]
one thing to note however, is that if you hit the button then go to the next match stage and back, the data is cleared (don't worry the data does not clear if you go between match stages and don't press the button)

**Comment by galaxygoldfish** [comment]
partially fixed, clear button can be added as a separate issue if it is needed in the future but for now, to get a viable product for week 4 it will not be included. the issue of going back deleting data has been solved
